name: Paradoxal
version: 1.0
description: Plugin IA du serveur paradoxal
author: Arisa02
main: IV.Paradoxal.Main.main
database: false

commands:
  panel:
    description: Ouvrir le menu
    aliases: [ugui,gui]
    permission: iv.panel.use
  chaos:
    description: Commande Chaos
    permission: iv.chaos.use

permissions:
  iv.*:
    description: Donne accées à tout les commande de IV
    children:
    iv.panel.*: true
    iv.panel.use: true
  iv.panel.*:
    description: Donne accées à tout le fonction du panel
  iv.panel.use:
    description: Autorise l'accées aux panel
  iv.ultima.*:
    description: Donne accées à tout les commande de Ultima
  iv.exodus.*:
    description: Donne accées à tout les commandes de Exodus
  iv.chaos.*:
    description: Donne accées à tout les commandes de Chaos
  iv.zalera.*:
    description: Donne accées à tout les commande de Zaléra
  
    